if room = room_ruins2
	text_id = "ruins_sign1"
if room = room_ruins3
	text_id = "ruins_sign2"
if room = room_ruins5
	text_id = "ruins_sign3"
if room = room_ruins9
	text_id = "ruins_sign4"
if room = room_ruins10
	text_id = "ruins_sign5"
if room = room_asrielroom
	text_id = "torhouse_asr_frame"
if room = room_area1
	text_id = "test2"