if global.menuno = 0
	global.menuno = 1
if global.menuno = 1
	global.menuno = 2
if global.menuno = 2
	global.menuno = 3
if global.menuno = 3
	global.menuno = 4
if global.menuno = 4
	global.menuno = 5
if global.menuno = 5
	global.menuno = 6
if global.menuno = 6
	global.menuno = 7
if global.menuno = 7
	global.menuno = 0