global.entrance = 11
instance_create_depth(0, 0, -99999, obj_persistentfader)
if (room == room_ruins13)
    room_goto(room_ruins14)
if (room == room_ruins14)
    room_goto(room_ruins13)
if (room == room_ruins16E)
    room_goto(room_ruins16A)
if (room == room_ruins17)
    room_goto(room_ruins20)
if (room == room_ruins20)
    room_goto(room_ruins17)
if (room == room_torhouse3)
    room_goto(room_torasgore)
if (room == room_torasgore)
    room_goto(room_torhouse3)
if (room == room_torhouse2)
	room_goto(room_torkitchen)
if (room == room_torkitchen)
	room_goto(room_torhouse2)
if (room == room_torhouse1)
	room_goto(room_basement1)
if (room == room_basement1)
	room_goto(room_torhouse1)
if (room == room_ruins6)
	room_goto(room_ruined1)
if (room == room_ruined1)
	room_goto(room_ruins6)
	